name: Solar Theme
baseurl: /solar-theme-jekyll
description: A stylish blog using the Solarized color palette

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
